### ISSUE TITLE
libraries needed to run the max31865

### ISSUE THREAD

**Issue by AgeBeeTen** [nimaltd/max31865#1]
Hi,
I tried to compile the sources on a Raspberry but I fail with several issues during compilation. There are several header files referenced which could not be found: gpio.h, device.h, spi.h, linux/ioport.h and so on.
It would be good to drop a hint how to prepare the system or include a description how to download the referenced libs.
Thanks, regards AgeBee

**Comment by nimaltd** [comment]
hello. this library for STM32 HAL. you should convert all gpio and spi functions to your hardware type.

**Comment by muhammadnurimansyah** [comment]
thanks for your help with this library

**Comment by nimaltd** [comment]
your welcome

**Comment by MatheusCaltran** [comment]
I'm using the STM32F4 so in this case I should:

  #include "stm32f4xx_hal_gpio.h"
   #include "stm32f4xx_hal_spi.h"

when I do this it gives:

![image](https://github.com/nimaltd/max31865/assets/88856093/23d716c0-b7ab-4880-9fe3-1fff8b97785f)

**Comment by nimaltd** [comment]
Please read readme.md
