### ISSUE TITLE
Speed of sensing

### ISSUE THREAD

**Issue by ghomeshe88** [nimaltd/max31865#2]
Hi Nima
thank you for your nice libraries.
I have problem with this library. It sense very slowly. I need to sense temperature in mili second. please help me.
best regard

**Comment by nimaltd** [comment]
آه. You can not get data with high accuracy

**Comment by ghomeshe88** [comment]
could you please offer me a high speed temperature sensor in range -20 to 150 degree?

**Comment by nimaltd** [comment]
LM35 is not bad. But maximum temperature is below than 150

**Comment by ghomeshe88** [comment]
ممنون بابت پاسخ گوییت نیما جان الان دمایی که کتابخونه داره نشون میده اکی هست ولی تغییر دما کلی زمان میبره کجای برنامه رو تغییر بدم یخورده سریع تر بشه؟
الان انگار برنامه داره یه میانگین میگیرهه

Ehsan Karami
Cell Phone : +98 919 672 6864
E-mail : ***@***.***
"Ifopportunity doesn't knock, build a door" 

    On Monday, April 12, 2021, 12:46:49 PM GMT+4:30, Nima Askari ----- نیما عسکری ***@***.***> wrote:  
 
 


LM35 is not bad. But maximum temperature is below than 150

**Comment by Ashrefnajjar** [comment]
hello thank you so much for this library but i don't know if i've done something wrong but i'm receiving a data that increments and not the actual temperature 
could it be the wiring that  went wrong ?
thanks.
