### ISSUE TITLE
I have 3 channels of max31865，but can only work in one channel

### ISSUE THREAD

**Issue by Mountain03** [nimaltd/max31865#5]
Max31865_init(&Max31865_1,&hspi1,SPI1_CS_GPIO_Port,SPI1_CS_Pin,_MAX31865_3WIRE,_MAX31865_FILT50HZ);
Max31865_init(&Max31865_2,&hspi2,SPI2_CS_GPIO_Port,SPI2_CS_Pin,_MAX31865_3WIRE,_MAX31865_FILT50HZ);
Max31865_init(&Max31865_3,&hspi3,SPI3_CS_GPIO_Port,SPI3_CS_Pin,_MAX31865_3WIRE,_MAX31865_FILT50HZ);

//Max31865_readTempC(&Max31865_1,&t1);
//printf("Max31865_1:%f		",t1);
	  	  
Max31865_readTempC(&Max31865_2,&t2);
printf("Max31865_2:%f		\n",t2);

when I only read one channel , the value is correct, but when I read two or three , the value become strange,I don't know where is the problem

**Comment by Mountain03** [comment]
hardware problem

**Comment by nimaltd** [comment]
hello. please try all of them on one spi and different CS pin
